version: "3.8"
services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    restart: always